# Generated by Django 5.1.7 on 2025-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='close_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='open_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
