# Generated by Django 5.1.7 on 2025-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_jobs_close_date_alter_jobs_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='close_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
