# Generated by Django 5.1.7 on 2025-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_jobs_salary_based_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Job_Type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part_Time', 'Part Time'), ('Remote', 'Remote')], default='Full Time', max_length=20),
        ),
    ]
