# Generated by Django 5.1.7 on 2025-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_jobs_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlr', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Job_Type',
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobType',
            field=models.ManyToManyField(related_name='job_type', to='mainapp.jobtype'),
        ),
    ]
