# Generated by Django 5.1.7 on 2025-03-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_applicant_applications_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='salary_based_on',
        ),
    ]
