# Generated by Django 5.1.7 on 2025-03-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_jobs_salary_based_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary_based_on',
            field=models.CharField(choices=[('p', 'permonth'), ('y', 'peryear')], help_text='Enter salary type', max_length=20),
        ),
    ]
