# Generated by Django 5.1.7 on 2025-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_jobs_salary_based_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='x',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
