# Generated by Django 5.1.7 on 2025-03-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_jobs_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='x',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_based_on',
            field=models.CharField(choices=[('Per Month', 'Per Month'), ('Per Year', 'Per Year')], default='Per Month', max_length=20),
        ),
    ]
