# Generated by Django 5.1.7 on 2025-03-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_jobs_x_alter_jobs_salary_based_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
