# Generated by Django 5.1.7 on 2025-04-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_jobs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mainapp.jobs'),
            preserve_default=False,
        ),
    ]
