# Generated by Django 5.1.7 on 2025-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_applications_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
